ERD/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Refreshment_Dashboard.Models
{
    public class Enrollment
    {

        [Key]
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int ActivityID { get; set; }

        [ForeignKey("EmployeeID")]
        public virtual Employee Employee { get; set; }

        [ForeignKey("ActivityID")]
        public virtual Activity Activity { get; set; }

        public int? TeamID { get; set; }
        [ForeignKey("TeamID")]
        public virtual Team Team { get; set; }

    }
}

ERD/Controllers/API/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Refreshment_Dashboard.Models;
using ERD.Services;

namespace ERD.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class EnrollmentsController : ControllerBase
    {
        private readonly EnrollmentService enrollmentService;

        public EnrollmentsController(EnrollmentService enrollment)
        {
            enrollmentService = enrollment;
        }

        // GET: api/EnrollmentsAPI
        [HttpGet]
        public ActionResult<IList<Enrollment>> GetEnrollment()
        {
            return enrollmentService.ListOfEnrollment().ToList();
        }

        // GET: api/EnrollmentsAPI/5
        [HttpGet("{id}")]
        public ActionResult<Enrollment> GetEnrollment(int id)
        {
            var enrollment = enrollmentService.GetEnrollmentDetails(id);

            if (enrollment == null)
            {
                return NotFound();
            }

            return enrollment;
        }

        // PUT: api/EnrollmentsAPI/5
        [HttpPut("{id}")]
        public ActionResult PutEnrollment(int id, Enrollment enrollment)
        {
            if (id != enrollment.ID)
            {
                return BadRequest();
            }
            else
            {
                enrollmentService.UpdateAnEnrollment(enrollment);
                return Ok();
            }
        }

        // POST: api/EnrollmentsAPI
        [HttpPost]
        public ActionResult<Enrollment> PostEnrollment(Enrollment enrollment)
        {
            var enroll = enrollmentService.AddAnEnrollment(enrollment);
            return Ok(enrollment);
        }


        // DELETE: api/EnrollmentsAPI/5
        [HttpDelete("{id}")]
        public ActionResult DeleteEnrollment(int id)
        {
            var enrollment = enrollmentService.GetEnrollmentDetails(id)
;
            if (enrollment == null)
            {
                return NotFound();
            }
            else
            {
                enrollmentService.DeleteAnEnrollment(enrollment);
                return Ok();
            }
        }


        //private bool EnrollmentExists(int id)
        //{
        //    return _context.Enrollments.Any(e => e.ID == id);
        //}
    }
}

ERD/Controllers/EnrollmentsController.cs
#nullable disable
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Refreshment_Dashboard.Models;
using Microsoft.Extensions.Logging;
using ERD.Services;
using ERD.Models;
using Microsoft.AspNetCore.Authorization;

namespace ERD.Controllers
{
    [Authorize]
    public class EnrollmentsController : Controller
    {
        private readonly ILogger<EnrollmentsController> _logger;
        private readonly ERDContext _context;
        
        private readonly EnrollmentService _enrollmentService;
        private readonly ActivitiesService _activitiesService;
        private readonly EmployeeService _employeeService;
        private readonly TeamsService _teamService;
        public string Message { get; set; } = string.Empty;
        public EnrollmentsController(ERDContext context, ILogger<EnrollmentsController> logger, EnrollmentService enrollmentService, ActivitiesService activitiesService, EmployeeService employeeService, TeamsService teamService )
        {
            _context = context;
            _enrollmentService = enrollmentService;
            _activitiesService = activitiesService;
            _employeeService = employeeService;
            _teamService = teamService;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected Enrollments Controller");
        }


        // GET: Enrollments
        public async Task<IActionResult> Index()
        {
            return View(_enrollmentService.ListOfEnrollment().ToList());
        }

        // GET: Enrollments/Details/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Details(int id)
        {
            
            var obj = _enrollmentService.GetEnrollmentDetails(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }



        // GET: Enrollments/Create
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            var TypeDropDown = _context.Employees.ToList();
            var TypeDropDown2 = _context.Activitys.ToList();
            var TypeDropDown3 = _context.Teams.ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;

            return View();
        }

        // POST: Enrollments/Create
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Enrollment enrollment)
        {
            var result = _enrollmentService.AddAnEnrollment(enrollment);
            if (result == "Successfully Enrolled")
                return RedirectToAction("Index");
            else if (result == "Enrollment already exists")
                ViewBag.Error = result;
            else if (result == "You can choose upto 4 activities only")
                ViewBag.Error = result;
            else if (result == "Max enrollment for team reached.")
                ViewBag.Error = result;

            var TypeDropDown = _context.Employees.ToList();
            var TypeDropDown2 = _context.Activitys.ToList();
            var TypeDropDown3 = _context.Teams.ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;

            return View(enrollment);

        }

        public IActionResult Exceeding_Enrollment()
        {
            return View();
        }

        public IActionResult Duplicate_Enrollment()
        {
            return View();
        }


        // GET: Enrollments/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _enrollmentService.GetEnrollmentDetails(id);

            var TypeDropDown = _context.Employees.ToList();
            var TypeDropDown2 = _context.Activitys.ToList();
            var TypeDropDown3 = _context.Teams.ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;
            return View(obj);
        }

        // POST: Enrollments/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Enrollment enrollment)
        {
           
            var TypeDropDown = _context.Employees.ToList();
            var TypeDropDown2 = _context.Activitys.ToList();
            var TypeDropDown3 = _context.Teams.ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            ViewBag.TypeDropDown2 = TypeDropDown2;
            ViewBag.TypeDropDown3 = TypeDropDown3;
            var result = _enrollmentService.UpdateAnEnrollment(id, enrollment);
            if (result == "Successfully Updated")
                return RedirectToAction("Index");
            else if (result == "Enrollment already exists")
                ViewBag.Error = result;
            else if (result == "Max enrollment for team reached")
                ViewBag.Error = result;
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(int id)
        {

            var obj = _enrollmentService.GetEnrollmentDetails(id);
            return View(obj);
            
        }

        // POST: Enrollments/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           
            var result = _enrollmentService.DeleteAnEnrollment(_enrollmentService.GetEnrollmentDetails(id));
            return RedirectToAction(nameof(Index));
        }
        private bool EnrollmentExists(int id)
            {
                return _context.Enrollments.Any(e => e.ID == id);
            }


        [HttpPost]
        public async Task<JsonResult> CallResult(int id)
        {
            var teamList = _teamService.AllTeam().Where(x => x.ActivityID == id).ToList();
            var teamDropDownItems = teamList.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.Name }).ToList();
            var returnValue = Json(teamDropDownItems);
            return Json(teamDropDownItems);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
    }

ERD/Views/Enrollments/Create.cshtml
@model Refreshment_Dashboard.Models.Enrollment

@{
    ViewData["Title"] = "Create";
    var employeeListDetails = ViewBag.TypeDropDown;
    var activityListDetails = ViewBag.TypeDropDown2;
    var teamListItem = ViewBag.TypeDropDown3;
}

<h1>Create</h1>

<h4>Enrollment</h4>
<hr />

<form method="post">

     <select asp-for ="EmployeeID">
           <option selected>--Choose Employee--</option>
           @foreach (var item in  employeeListDetails)
                    {
                        <option value="@item.ID">@item.Firstname</option>
                    }
       </select>

    <select asp-for="ActivityID">
        <option selected>--Select An Activity--</option>
        @foreach (var item in activityListDetails)
        {
            <option value="@item.ID">@item.Name</option>
        }
    </select>

    <select asp-for="TeamID">
        <option selected>--Select Team--</option>
        @foreach (var item in teamListItem)
        {
            <option value="@item.ID">@item.Name</option>
        }
    </select>
    <br />
    <br />
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>

    <p style="color:red;">
        @Html.Label("",Convert.ToString((string)ViewBag.ExistingActivityError))
    </p>
    <p style="color:red;">
        @Html.Label("",Convert.ToString((string)ViewBag.ExceedingActivityError))
    </p>
    <br />
 
    <script >
        $(function () {
            $('#EmployeeID').multiselect({
                includeSelectAllOption: true
            });
        });
    </script> 


    @section scripts{
    <script>
        $(document).ready(function(){
          $("#ActivityID").change(function(){
            var selectedIds = $(this).val();
              $.ajax({url: '@Url.Action("CallResult" , "Enrollments")', type:"post", data:{id:selectedIds} ,success: function(result){
              if(result != null)
              {
                  $("#TeamID").empty();
                    $.each(result, function (i,value) {
                        $("#TeamID").append($("<option></option>").val(value.value).html(value.text));
                    });
              }
            }});
          });
        });
    </script>
    }

    

</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ERD/Views/Enrollments/Delete.cshtml
@model Refreshment_Dashboard.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ERD/Views/Enrollments/Details.cshtml
@model Refreshment_Dashboard.Models.Enrollment

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
         <dt class = "col-sm-2">
            Enrollment ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            Employee ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeID)
        </dd>
         <dt class = "col-sm-2">
            Employee Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.Firstname)
        </dd>
        <dt class = "col-sm-2">
            Activity ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activity.ID)
        </dd>
         <dt class = "col-sm-2">
            Activity Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activity.Name)
        </dd>
        <dt class = "col-sm-2">
            Team ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team.ID)
        </dd>
         <dt class = "col-sm-2">
            Team Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Team.Name)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ERD/Views/Enrollments/Edit.cshtml
@model Refreshment_Dashboard.Models.Enrollment

@{
    ViewData["Title"] = "Edit";
    var employeeListItem = ViewBag.TypeDropDown;
    var activityListItem = ViewBag.TypeDropDown2;
    var teamListItem = ViewBag.TypeDropDown3;
}

<h1>Edit</h1>

<h4>EmployeeActivity</h4>
<hr />

<form method ="post">
  <br />
  
    <select asp-for ="EmployeeID">
           <option selected>--Employee--</option>
            @foreach (var item in employeeListItem)
                    {
                        <option value="@item.ID">@item.Firstname</option>
                    }
       </select>
    <br />
    <br />
        <select asp-for ="ActivityID">
           <option selected>--Activity--</option>
            @foreach (var item in activityListItem)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
       </select>
       <br />
       <br />
       <select asp-for ="TeamID">
           <option selected>--Venue--</option>
            @foreach (var item in teamListItem)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
       </select>
       <br />
       <br />

   <button type ="submit" class= "btn btn-primary">
       Edit
   </button>

    <p style = "color:red;">
           @Html.Label("",Convert.ToString((string)ViewBag.Error))
       </p> 
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts{
    <script>
$(document).ready(function(){
  $("#ActivityID").change(function(){
    var selectedIds = $(this).val();
      $.ajax({url: '@Url.Action("CallResult" , "Enrollments")', type:"post", data:{id:selectedIds} ,success: function(result){
      if(result != null)
      {
          $("#TeamID").empty();
            $.each(result, function (i,value) {
                $("#TeamID").append($("<option></option>").val(value.value).html(value.text));
            });
      }
    }});
  });
});
</script>
}

ERD/Views/Enrollments/Index.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model IEnumerable<Refreshment_Dashboard.Models.Enrollment>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h1>Enrolled Employees </h1></center>

@if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
{
    <p>
        <a asp-action="Create">Enroll New Employee</a>
    </p>
}
<table class="table">
        <thead>
            <tr>
                <th>Enrollment No.</th>
                <th>Activity Name</th>
                <th>Employee Name</th>
                <th>Team</th>
                 @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
{
                <th>Action</th>
}
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.ID
                    </td>
                    <td>
                        @item.Activity.Name
                    </td>
                    <td>
                        @item.Employee.Firstname
                    </td>
                    <td>
                        @item.Team.Name
                    </td>

                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
                    {
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>