ERD/Controllers/TeamsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Refreshment_Dashboard.Models;
using ERD.ViewModels;
using ERD.Services;
using Microsoft.AspNetCore.Authorization;

namespace ERD.Controllers
{
    [Authorize]
    public class TeamsController : Controller
    {
        private readonly ILogger<TeamsController> _logger;
        private readonly TeamsService _teamService;
        private readonly ActivitiesService _activitiesService;

        public TeamsController(ILogger<TeamsController> logger, TeamsService teamService, ActivitiesService activitiesService)
        {
            _teamService = teamService;
            _activitiesService = activitiesService;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into Teams Controller");
        }

        // GET: TeamsController
        public ActionResult Index()
        {
            return View(_teamService.AllTeam().ToList()); 
        }

        // GET: TeamsController/Details/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Details(int id)
        {
            var obj = _teamService.GetTeamDetails(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        // GET: TeamsController/Create
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View();
        }

        // POST: TeamsController/Create
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Team team)
        {
            var result = _teamService.CreateNewTeam(team);
            if (result == "Successfully Created")
                return RedirectToAction("Index");
            else if (result == "Team already exists")
                ViewBag.DuplicateError = result;

            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View(team);
        }
        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }

        // GET: TeamsController/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _teamService.GetTeamDetails(id);

            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }

        // POST: TeamsController/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Team team)
        {
            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            var result = _teamService.UpdateTeam(id, team);
            if (result == "Successfully Updated")
                return RedirectToAction("Index");
            else if (result == "Team already exists ")
                ViewBag.DuplicateError = result;
            return View(team);
        }

        // GET: TeamsController/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(int id)
        {
            var obj = _teamService.GetTeamDetails(id);
            return View(obj);
        }

        // POST: TeamsController/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _teamService.DeleteTeam(_teamService.GetTeamDetails(id));
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

ERD/Controllers/VenuesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Refreshment_Dashboard.Models;
using ERD.ViewModels;
using ERD.Services;
using ERD.Service;
using Microsoft.AspNetCore.Authorization;

namespace ERD.Controllers
{
    [Authorize]
    public class VenuesController : Controller
    {
        //private readonly ERDContext _context;
        private readonly ILogger<VenuesController> _logger;
        private readonly VenueService _venueService;
        private readonly ActivitiesService _activitiesService;

        public VenuesController(ILogger<VenuesController> logger, VenueService venueService, ActivitiesService activitiesService)
        {
            //_context = context;
            _venueService = venueService;
            _activitiesService = activitiesService;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into Venues Controller");
        }


        public async Task<IActionResult> Index()
        {
            return View(_venueService.ListOfVenues().ToList());
        }

        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Details(int id)
        {
            var obj = _venueService.GetVenueDetails(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }


        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View();
        }



        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Venue venue)
        {
            var result = _venueService.AddVenue(venue);
            if (result == "Successfully Added")
                return RedirectToAction("Index");
            else if (result == "Venue already exists")
                ViewBag.Error = result;

            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            return View(venue);
        }

        public IActionResult OverLimit()
        {
            return View();
        }

        public IActionResult Duplicate()
        {
            return View();
        }

        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var obj = _venueService.GetVenueDetails(id);

            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }

        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Venue venue)
        {
            
            var TypeDropDown = _activitiesService.ListOfActivities().ToList();

            ViewBag.TypeDropDown = TypeDropDown;

            var result = _venueService.UpdateVenue(id, venue);
            if (result == "Successfully Updated")
                return RedirectToAction("Index");
            else if (result == "Venue already exists")
                ViewBag.Error = result;
            return View(venue);
            
        }

        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(int id)
        {
            var obj = _venueService.GetVenueDetails(id);
            return View(obj);
        }

        [Authorize(Roles = "SuperAdmin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = _venueService.DeleteVenue(_venueService.GetVenueDetails(id));
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

ERD/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

ERD/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ERD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ERD.styles.css" asp-append-version="true" />
    <link href="http://cdn.rawgit.com/davidetutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ERD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Activities" asp-action="Index">Activities On Board</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Teams" asp-action="Index">Teams</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Enrollments" asp-action="Index">Enrollments</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Bookings" asp-action="Index">Booked Matches</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Venues" asp-action="Index"> Venues</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                            </li>

                            @if (SignInManager.IsSignedIn(User) && User.IsInRole("SuperAdmin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Role" asp-action="ListOfRoles">Manage Roles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Role" asp-action="ListOfUsers">Manage Users</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/15/bootstrap-multiselect.is"></script>

    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ERD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>